google_email: "you@gmail.com"
google_password: "intense!"
oauth_file_name: "oauth.cred"
media_monkey_db_path: "C:\Users\You\AppData\Roaming\MediaMonkey\MM.DB"

media_monkey_playlists:
  - Coldplay
  - Kaskade